const USER_LOGGED = "USER_LOGGED";
const USER_LOGOUT = "USER_LOGOUT";
const URL_API = "http://localhost:8000";
const SHOW_POPUP = "SHOW_POPUP";
const HIDDEN_POPUP = "HIDDEN_POPUP";



export {USER_LOGGED, USER_LOGOUT, URL_API, SHOW_POPUP, HIDDEN_POPUP };

